name: Build & Deploy
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v6

      - name: Install deps
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          path: build
          name: build-files # cкладываем сюда

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build project
        uses: actions/download-artifact@v8
        with:
          name: build-files # берем от сюда
