name: Deploy Angular App
on: push
jobs:
  test:
    # запускаем на ubuntu
    runs-on: ubuntu-latest
    steps:
      # берем текущий код с виртуальной машины
      - name: Get repository code
        uses: actions/checkout@v6

      # установка зависимостей
      - name: Install dependencies
        run: npm ci

      # запускаем скрипт
      - name: Test application
        run: npm run test
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v6

      - name: Install dependencies
        run: npm ci

      - name: Lint application
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v6

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Deploy
        run: echo Deploying...
